jobs:
- job: StopAgent
  displayName: 'Stop Agent'
  pool:
    name: default
  steps:
  - powershell: |
      Stop-Service -Name "두지수01Agent" -ErrorAction SilentlyContinue
    displayName: 'Stop 두지수01Agent'
